spring.application.name=BasTrackingSystemV3

# Sambungan ke Database SQLite
spring.datasource.url=jdbc:sqlite:upm_bus.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Konfigurasi JPA / Hibernate untuk SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=create-drop
#/if nak history
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

ngrok.authtoken=${NGROK_AUTHTOKEN:}
